allure.results.directory=target/allure-results
allure.link.issue.pattern=https://your-jira.com/browse/{}
allure.link.tms.pattern=https://your-testmanagement.com/{}
allure.link.mylink.pattern=https://example.org/{}